platform :ios, '9.0'

target 'mobile' do
  pod 'Firebase/Core'
  pod 'RNFirebase', :path => '../node_modules/react-native-firebase'
  pod 'Firebase/Auth'
  pod 'Firebase/Database'

  pod 'yoga', :path => '../node_modules/react-native/ReactCommon/yoga'
    pod 'React', :path => '../node_modules/react-native', :subspecs => [
      'BatchedBridge', # Required For React Native 0.45.0+
      'Core',
      'DevSupport'
    ]

  target 'mobileTests' do
    inherit! :search_paths
  end
end

target 'mobile-tvOS' do
  target 'mobile-tvOSTests' do
    inherit! :search_paths
  end
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    if target.name == "React"
      target.remove_from_project
    end
  end
end
